GraphMakie docs update
SciML/Catalyst.jl pull request #1130
Opened 2024-11-21 19:10 UTC by vyudu

Update docs and drop Graphviz dependency. Ran into an issue on my machine where `ExpandTemplates` was hanging for a really long time, so I changed some of the `@example` blocks to just ```julia, but it was still sort of hanging on the machine so not sure what's happening. In any case wanted to see how it did on the CI.

2024-11-21 19:44 UTC, isaacsas commented
You need to also update all the places in the current docs where we dynamically build graphs to use the new code.

2024-11-21 20:08 UTC, isaacsas commented
GLMakie tests are failing?

2024-11-21 20:14 UTC, isaacsas commented
ok

2024-11-23 14:52 UTC, isaacsas commented
Seems like somehow the `plot` from Makie is getting loaded now even in tutorials that don't use Makie for plotting?

2024-11-23 15:03 UTC, vyudu commented
seems like it was because GLMakie is loaded in that `@example` block, added an explicit import to fix

2024-11-23 15:43 UTC, isaacsas commented on docs/src/introduction_to_catalyst/introduction_to_catalyst.md
> +using Catalyst, GraphMakie, GLMakie
Can you just import `GraphMakie` and `GLMakie` and still use `plot_network`? If so, then you could still `using Plots` which is probably a more relevant workflow for most users.

2024-11-26 01:04 UTC, isaacsas commented
You seem to be getting hit by the same NonlinearSolve related doc build error I was seeing. This seems to have just appeared in the last day or so.

2024-11-26 14:54 UTC, ChrisRackauckas commented
Are you referring to the Cassette one? Has anyone upstreamed an issue to Cassette yet?

2024-11-26 19:04 UTC, vyudu commented
I think this needs to merge after #1138 since I fix the other doc build error in that PR

2024-12-12 14:25 UTC, isaacsas requested changes
@vyudu I'll merge after you address my comments and I confirm the docs look ok with this. Thanks!

2024-12-12 14:25 UTC, isaacsas commented on docs/src/index.md
> +- The GraphMakie package has [Makie](https://docs.makie.org/stable/) recipes that can be used to generate and [visualize reaction network graphs](@ref visualisation_graphs)
```suggestion
- [GraphMakie](https://docs.makie.org/stable/) recipes are provided that can be used to generate and [visualize reaction network graphs](@ref visualisation_graphs) 
```

2024-12-12 14:25 UTC, isaacsas commented on test/runtests.jl
> +        @time @safetestset "Graph visualization" begin include("extensions/graphmakie.jl") end
Isn't this already in the extensions test section? (Which is more appropriate for it.)

2024-12-20 16:53 UTC, isaacsas commented
@vyudu the generated graph in the doc artifact for the introductory tutorial looks pretty bad (it seems to have lines crossing). I thought this was supposed to be fixed?

2024-12-20 16:58 UTC, isaacsas requested changes

2024-12-20 16:58 UTC, isaacsas commented on docs/src/model_creation/model_visualisation.md
> +plot_complexes(brusselator)
This also ends up looking pretty bad, with a huge amount of white space.

2024-12-20 16:58 UTC, isaacsas commented on docs/src/model_creation/network_analysis.md
> +g = plot_network(repressilator)
The generated graph here and in the tutorial seems to have lines crossing unnecessarily?

2024-12-20 16:58 UTC, isaacsas commented on docs/src/model_creation/network_analysis.md
> +plot_complexes(repressilator)
This graph looks quite mess due to the Hill functions. Can you disable the labels on the lines for it?

2024-12-20 16:58 UTC, isaacsas commented on docs/src/model_creation/network_analysis.md
> +plot_complexes(rn)
Similar comment about dropping edge labels, and about the huge amount of white space.

2024-12-20 16:58 UTC, isaacsas commented on docs/src/model_creation/network_analysis.md
> +plot_complexes(rn)
Huge amount of white space and tiny graphs.

2025-01-06 17:42 UTC, vyudu commented
Let's see how these look. I need to think about how to reduce the amount of whitespace though. I think it should do a bit better with `Stress()` but it might not be good enough.

2025-01-06 17:47 UTC, vyudu commented
Removed most of the GLMakie instances in the docs but there's still a `GLMakie` instance in [the interactive Brusselator doc](https://github.com/SciML/Catalyst.jl/blob/master/docs/src/model_simulation/examples/interactive_brusselator_simulation.md).

2025-01-06 17:52 UTC, isaacsas commented
(I removed all GLMakie doc dependencies last week I thought.)

2025-01-06 17:55 UTC, vyudu commented
Check the last two commits, I changed a couple instances there? But let me know if I did something wrong

2025-01-07 15:30 UTC, isaacsas commented on docs/src/introduction_to_catalyst/introduction_to_catalyst.md
>  blue node, and each reaction as an orange dot. Black arrows from species to
This needs updating for the new colors / meaning of components of the graphs.

2025-01-07 15:32 UTC, isaacsas commented on docs/src/model_creation/model_visualisation.md
> +Here, reaction complexes are displayed as blue nodes, and reactions between complexes are displayed as black arrows. Edges are labeled with their rate expressions.
Edges aren't labeled in the generated graph? Is this the correct behavior for `plot_complexes`, if so the text needs updating, if not the code needs updating.

2025-01-09 13:04 UTC, isaacsas commented
Looks like there is a bad link in one of the new doc files?

2025-01-09 13:14 UTC, isaacsas commented
Oh, this needs to also remove this stuff in Catalyst.jl that loads the GraphViz.jll: 

https://github.com/SciML/Catalyst.jl/blob/b7d8c61081075479e3e919986bbcae64775b3088/src/Catalyst.jl#L63-L74

2025-01-09 13:34 UTC, isaacsas commented
Is it linked via a docstring?

2025-01-09 13:39 UTC, vyudu commented
Ah I see. But in that case I don't know why it's resolving to Main or CatalystGraphMakieExtension and not looking in Catalyst.

2025-01-09 13:49 UTC, isaacsas commented on docs/src/api.md
> +Catalyst.ReactionComplex
This worked completely fine before (for example, the current docs). Why would this be the underlying issue?

2025-01-09 13:54 UTC, vyudu commented on docs/src/api.md
> +Catalyst.ReactionComplex
Hm yeah this doesn't make sense. But I don't understand what could cause the error it raises otherwise, will keep looking.

2025-01-09 18:35 UTC, merged