Tutorial for (mostly Symbol based) interfacing with problems, integrators, and solutions
SciML/Catalyst.jl pull request #639
Opened 2023-04-12 14:15 UTC by TorkelE

Add a new tutorial on how to e.g. do `sol[:X1]` to get solution values of `X1`. Also mentioned remake and how to do
```
@unpack X1 = rn
```
and use `X1` instead of `:X1`. 

Makes minor modifications in the callback and plotting description of the advanced simulation tutorial to use this notation.

2023-04-12 14:18 UTC, TorkelE commented
This should be ready for merging, if checks pass.

2023-04-13 18:03 UTC, isaacsas requested changes

2023-04-13 18:03 UTC, isaacsas commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +and then uses these to build systems of equations. Here, these symbolic variables (`x`, `y`, and `z`) and parameters (`σ`, `ρ`, and `β`) can be used to interface a `problem`, `integrator`, and `solut
As you can also get them via `rn.X1`, thereby avoiding `@unpack`, I wouldn't say they can't be used directly.

2023-04-13 18:03 UTC, isaacsas commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +Here, we first list the parameters and variables (for reaction systems called "species") we which to import (in this case we select all, but we could select only a subset), next we denote from which
```suggestion
Here, we first list the parameters and variables (for reaction systems the latter are typically species) we wish to import (in this case we select all, but we could select only a subset), next we denote from which model (here `rn`) from which we wish to import from. Next, these values can be used directly to interface with e.g. an `ODEProblem`:
```

2023-04-13 18:03 UTC, isaacsas commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +u0 = [:X1 => 1.0, :X2 => 5.0]
```suggestion
u0 = [X1 => 1.0, X2 => 5.0]
```
Show `u0` and `p` can be built with the symbolic parameters too?

2023-04-13 18:18 UTC, TorkelE commented on docs/src/catalyst_applications/advanced_simulations.md
> +sol = solve(deepcopy(jprob), SSAStepper(); callback=cb)
I though `deepcopy` was the way to go for complicated structures with other structures within them? Happy to be corrected though.

2023-04-13 18:19 UTC, TorkelE commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +again, using a similar syntax to problems, we can get the values of a state:
Is this something that anyone would actually ever do? Just wanted to somehow acquire an integrator to show how stuff worked on.

2023-04-13 18:21 UTC, ChrisRackauckas commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +again, using a similar syntax to problems, we can get the values of a state:
Yes, it's useful in animations, interactive contexts, GUIs, and such.,

2023-04-13 18:24 UTC, TorkelE commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +again, using a similar syntax to problems, we can get the values of a state:
Excellent. Maybe it would make sense to add that to the "advanced simulation tutorials" and just link that one from here?

2023-04-13 18:28 UTC, isaacsas commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +oprob[:X1] = 10.0
Maybe a better example here is to run and plot like 10 solutions. Then you would to keep the original around as indeed I think you'd have an issue without using copies with the mutation (i.e. the problem would be in an inconsistent state on the next simulation). Then you can use `deepcopy`, but I'd also add an explanation then for why it is needed.

2023-04-13 18:29 UTC, TorkelE commented on docs/src/catalyst_applications/advanced_simulations.md
> +sol = solve(deepcopy(jprob), SSAStepper(); callback=cb)
Admittedly this is the last `solve` of the problem in this example, but assuming hypothetical following code this seems sensible though? Or imagine someone just rerunning that last line 2-3 times to see different solutions.

It feels like good practise to pass a copy of the problem when using mutating callbacks.

2023-04-13 18:34 UTC, TorkelE commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +oprob[:X1] = 10.0
Doing an ensemble would make sense, but wanted to keep this example focused, and not start repeating what we have in other tutorial. Should explain more in depth though, agreed.

2023-04-13 18:35 UTC, isaacsas commented on docs/src/catalyst_applications/advanced_simulations.md
> +sol = solve(deepcopy(jprob), SSAStepper(); callback=cb)
Maybe a better example here is to run and plot like 10 solutions. Then you would need to keep the original around as indeed I think you'd have an issue without using deep copies due to the mutation (i.e. the problem would be in an inconsistent state on the next simulation). Then you can use `deepcopy`, but I'd also add an explanation then for why it is needed.

2023-04-13 18:36 UTC, isaacsas commented on docs/src/catalyst_applications/advanced_simulations.md
> +sol = solve(deepcopy(jprob), SSAStepper(); callback=cb)
But to be honest, the better approach would be to show users how to then reset things via mutation of the original problem again to have the original values.

2023-04-13 18:38 UTC, TorkelE commented on docs/src/catalyst_applications/advanced_simulations.md
> +sol = solve(deepcopy(jprob), SSAStepper(); callback=cb)
Wanted to keep the example focused, and not make a full ensemble as that is pretty much a repeat of another tutorial. Will do some more explaining of deepcopy, and link the ensemble example where I actually show why the `deepcopy` is important.

2023-04-13 18:39 UTC, TorkelE commented on docs/src/catalyst_applications/advanced_simulations.md
> +sol = solve(deepcopy(jprob), SSAStepper(); callback=cb)
> But to be honest, the better approach would be to show users how to then reset things via mutation of the original problem again to have the original values.

How you mean, just reset the value after the simulation has finished?

2023-04-13 18:39 UTC, isaacsas commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +again, using a similar syntax to problems, we can get the values of a state:
Also useful for resetting a simulation without reinitializing all the cache structures I believe.

https://docs.sciml.ai/DiffEqDocs/stable/basics/integrator/

2023-04-27 13:53 UTC, TorkelE commented on docs/src/catalyst_applications/simulation_structure_interfacing.md
> +oprob[:X1] = 10.0
fixed.

2023-04-27 13:59 UTC, TorkelE commented on docs/src/catalyst_applications/advanced_simulations.md
> +sol = solve(deepcopy(jprob), SSAStepper(); callback=cb)
Ok, so this example is proceeded by one where we explain, with examples, why `deepcopy` is needed (line 185 to 265). I think is is well explained, but tell me if you think there should be further changes.

2023-04-27 17:23 UTC, isaacsas commented
Could you fix the examples that are failing and giving errors when building the docs? 

After that feel free to merge -- I can't really read through till mid-next week, and I can just tweak it if I want to update anything at that time.

2023-04-27 18:53 UTC, merged