Separate conservation law page
SciML/Catalyst.jl pull request #998
Opened 2024-07-21 22:00 UTC by TorkelE

Splits the conservation law page to a separate page.

2024-07-21 22:04 UTC, TorkelE commented
ready

2024-07-22 14:38 UTC, isaacsas requested changes
Couple wording tweaks, feel free to merge when you are happy.

2024-07-22 14:38 UTC, isaacsas commented on docs/src/model_creation/conservation_laws.md
> +Catalyst contain specialised functionality to work with *conserved quantities*, i.e. species quantities which are conserved throughout e.g. a simulation. This functionality is both automatically util
```suggestion
Catalyst can detect, and eliminate for differential-equation based models, *conserved quantities*, i.e. linear combinations of species which are conserved via the chemistry. This functionality is both automatically utilised by Catalyst (e.g. to [remove singular Jacobians during steady state computations](@ref homotopy_continuation_conservation_laws)), but is also available for users to utilise directly (e.g. to potentially [improve simulation performance](@ref ode_simulation_performance_conservation_laws)).
```

2024-07-22 14:38 UTC, isaacsas commented on docs/src/model_creation/conservation_laws.md
> +    Currently, there is a bug in MTK where the values associated with conservation laws are not updated properly in response to [`remake`](@ref simulation_structure_interfacing_problems_remake) (or [
```suggestion
    Currently, there is a bug in MTK where the parameters, `Γ`, associated with conservation laws are not updated properly in response to [`remake`](@ref simulation_structure_interfacing_problems_remake) (or [other problem-updating functions, such as `getu`](@ref simulation_structure_interfacing_functions)). Hence, problems created using `remove_conserved = true` *should not* be modified, i.e. by changing initial conditions or the values of the `Γ`'s directly. Instead, to change these values new problems must be generated with the new initial condition map.
```

2024-07-22 18:33 UTC, merged